function createfigure(XData1, X1, YMatrix1)
%CREATEFIGURE(XData1, X1, YMatrix1)
%  XDATA1:  line xdata
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 10-Sep-2021 11:08:37

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Tag','dummyAxesForLegend','Parent',figure1,...
    'Position',[0.1 0.1 0.01 0.01]);
axis off

% Create line
line(XData1,XData1,'DisplayName','[Peripheral Compartment].P',...
    'Tag','dummyLineForLegend',...
    'Parent',axes1,...
    'LineWidth',1.5);

% Create line
line(XData1,XData1,'DisplayName','[Serum Compartment].S',...
    'Tag','dummyLineForLegend',...
    'Parent',axes1,...
    'LineStyle','-.');

% Create line
line(XData1,XData1,'DisplayName','[Retinal Compartment].R',...
    'Tag','dummyLineForLegend',...
    'Parent',axes1,...
    'LineStyle',':');

% Create line
line(XData1,XData1,'DisplayName','[Vitrious Compartment].V',...
    'Tag','dummyLineForLegend',...
    'Parent',axes1,...
    'LineStyle','--');

% Create line
line(XData1,XData1,'DisplayName','[Aqueous Compartment].A',...
    'Tag','dummyLineForLegend',...
    'Parent',axes1);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.830271321265965 0.883508774478707 0.164728678734035 0.0964912255212926],...
    'Interpreter','none');
title(legend1,'Response');

% Create axes
axes2 = axes('Tag','labelAxes','Parent',figure1);
axis off

% Create ylabel
ylabel('millimole','Units','pixels','Interpreter','none','Visible','on');

% Create xlabel
xlabel('time (second)','Units','pixels','Interpreter','none','Visible','on');

% Set the remaining axes properties
set(axes2,'OuterPosition',...
    [0.00872093023255814 0.00986842105263158 0.815891472868217 0.978070175438596]);
% Create axes
axes3 = axes('Parent',figure1);
hold(axes3,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes3,...
    'Color',[0 0.447058823529412 0.741176470588235]);
set(plot1(2),'LineStyle','--');
set(plot1(3),'LineStyle',':');
set(plot1(4),'LineStyle','-.');
set(plot1(5),'LineWidth',1.5);

box(axes3,'on');
hold(axes3,'off');
% Set the remaining axes properties
set(axes3,'GridColor',...
    [0.149019607843137 0.149019607843137 0.149019607843137],'OuterPosition',...
    [0.0277777772290916 0.0314327485380117 0.796350129198966 0.955409356725146],...
    'PickableParts','all','TickLabelInterpreter','none','XGrid','on','YGrid',...
    'on');
